---
- include: apps/homebrew.yml tags=apps
- include: apps/sublime.yml tags=apps
- include: apps/dropbox.yml tags=apps
- include: apps/chrome.yml tags=apps
- include: apps/firefox.yml tags=apps
- include: apps/virtualbox.yml tags=apps
- include: apps/vagrant.yml tags=apps
- include: apps/nodejs.yml tags=apps

- hosts: all
  user: ryanvangundy
  connection: local

  pre_tasks:
    - name: Create Ansible downloads directory
      file: path={{ downloads }} state=directory
      tags: ['common']
    - name: Get user's name
      sudo: no
      command: whoami
      register: user_name
      tags: ['common']

  vars_prompt:
    - name: "projects_folder"
      prompt: "Enter your root projects folder"
      default: "Documents"
      private: no
    - name: "project_name"
      prompt: "Name your project"
      default: "myProject"
      private: no
    - name: "remote_repo_url"
      prompt: "Enter a remote repository URL"
      private: no

  vars:
    - downloads: ~/.ansible-downloads/
    - project_path: "/Users/{{ user_name.stdout }}/{{ projects_folder }}/{{ project_name }}"

  roles:
    - { role: scaffolds/dev, tags: ['dev'] }
    - { role: scaffolds/node, tags: ['node'] }
    - { role: scaffolds/vagrant, tags: ['vagrant'] }
    - { role: scaffolds/git, tags: ['git'] }