---
- name: Install ruby-gems
  gem: name={{ item }}
  with_items: ruby_gems

- name: Install global npm packages
  npm: name={{ item }} global=yes
  with_items: npm_global_packages

- name: Install project npm packages from package.json
  npm: path={{ project_path }} production=yes
