---
- name: Establish ansible roles
  copy: src="roles/{{ item }}" dest="{{ project_path }}/provisioning/roles" force=no
  with_items: project_roles

- name: Copy package.json
  template: src=package.json.j2 dest="{{ project_path }}/package.json" force=no

- name: Copy app folder
  copy: src="app" dest="{{ project_path }}" force=no