---
- name: Initialize the git repository
  command: git init
  args:
    chdir: "{{ project_path }}"
    creates: "{{ project_path }}/.git"

- name: Add first project files to repo
  command: git add . chdir={{ project_path }}

- name: Get commit count
  command: git rev-list HEAD --count chdir={{ project_path }}
  ignore_errors: yes
  register: git_commit_count

- name: Make first commit
  command: git commit -m 'Initial commit' chdir={{ project_path }}
  when: git_commit_count|failed

- name: Get current remote URL
  command: git remote show origin chdir={{ project_path }}
  ignore_errors: yes
  register: git_remote_url

- name: Add remote origin
  command: git remote add origin {{ remote_repo_url }} chdir={{ project_path }}
  when: remote_repo_url != '' and git_remote_url|failed