---
- hosts: all
  connection: local
  vars:
    app_name: Google\ Chrome
    app_name_pretty: Google Chrome
    app_url: "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Google\ Chrome/
    creates: /Applications/Google\ Chrome.app
    downloads: ~/.ansible-downloads/

  tasks:
   - include: ../install/{{ install_method }}.yml